"""Represents each unique weapon in Starcraft.

These are primarily used to determine a unit's damage and upgrade damage in the
UNIS/UNIX sections.  There are 100 weapons in original Starcraft and 130 in Brood War.
"""


from ....model.richchk.richchk_enum import RichChkEnum

_NUM_SCM_WEAPONS = 100
_NUM_SCX_WEAPONS = 130


class WeaponId(RichChkEnum):
    GAUSS_RIFLE_NORMAL = (0, "Gauss Rifle Normal")
    GAUSS_RIFLE_JIM_RAYNORMARINE = (1, "Gauss Rifle Jim Raynormarine")
    C10_CONCUSSION_RIFLE_NORMAL = (2, "C10 Concussion Rifle Normal")
    C10_CONCUSSION_RIFLE_SARAH_KERRIGAN = (3, "C10 Concussion Rifle Sarah Kerrigan")
    FRAGMENTATION_GRENADE_NORMAL = (4, "Fragmentation Grenade Normal")
    FRAGMENTATION_GRENADE_JIM_RAYNORVULTURE = (
        5,
        "Fragmentation Grenade Jim Raynorvulture",
    )
    SPIDER_MINES = (6, "Spider Mines")
    TWIN_AUTOCANNONS_NORMAL = (7, "Twin Autocannons Normal")
    HELLFIRE_MISSILE_PACK_NORMAL = (8, "Hellfire Missile Pack Normal")
    TWIN_AUTOCANNONS_ALAN_SCHEZAR = (9, "Twin Autocannons Alan Schezar")
    HELLFIRE_MISSILE_PACK_ALAN_SCHEZAR = (10, "Hellfire Missile Pack Alan Schezar")
    ARCLITE_CANNON_NORMAL = (11, "Arclite Cannon Normal")
    ARCLITE_CANNON_EDMUND_DUKE = (12, "Arclite Cannon Edmund Duke")
    FUSION_CUTTER = (13, "Fusion Cutter")
    FUSION_CUTTER_HARVEST = (14, "Fusion Cutter Harvest")
    GEMINI_MISSILES_NORMAL = (15, "Gemini Missiles Normal")
    BURST_LASERS_NORMAL = (16, "Burst Lasers Normal")
    GEMINI_MISSILES_TOM_KAZANSKY = (17, "Gemini Missiles Tom Kazansky")
    BURST_LASERS_TOM_KAZANSKY = (18, "Burst Lasers Tom Kazansky")
    ATS_LASER_BATTERY_NORMAL = (19, "Ats Laser Battery Normal")
    ATA_LASER_BATTERY_NORMAL = (20, "Ata Laser Battery Normal")
    ATS_LASER_BATTERY_NORAD_II_MENGSK_DUGALLE = (
        21,
        "Ats Laser Battery Norad Ii Mengsk Dugalle",
    )
    ATA_LASER_BATTERY_NORAD_II_MENGSK_DUGALLE = (
        22,
        "Ata Laser Battery Norad Ii Mengsk Dugalle",
    )
    ATS_LASER_BATTERY_HYPERION = (23, "Ats Laser Battery Hyperion")
    ATA_LASER_BATTERY_HYPERION = (24, "Ata Laser Battery Hyperion")
    FLAME_THROWER_NORMAL = (25, "Flame Thrower Normal")
    FLAME_THROWER_GUI_MONTAG = (26, "Flame Thrower Gui Montag")
    ARCLITE_SHOCK_CANNON_NORMAL = (27, "Arclite Shock Cannon Normal")
    ARCLITE_SHOCK_CANNON_EDMUND_DUKE = (28, "Arclite Shock Cannon Edmund Duke")
    LONGBOLT_MISSILES = (29, "Longbolt Missiles")
    YAMATO_GUN = (30, "Yamato Gun")
    NUCLEAR_MISSILE_WEAPON = (31, "Nuclear Missile Weapon")
    LOCKDOWN = (32, "Lockdown")
    EMP_SHOCKWAVE = (33, "Emp Shockwave")
    IRRADIATE = (34, "Irradiate")
    CLAWS_NORMAL = (35, "Claws Normal")
    CLAWS_DEVOURING_ONE = (36, "Claws Devouring One")
    CLAWS_INFESTED_KERRIGAN = (37, "Claws Infested Kerrigan")
    NEEDLE_SPINES_NORMAL = (38, "Needle Spines Normal")
    NEEDLE_SPINES_HUNTER_KILLER = (39, "Needle Spines Hunter Killer")
    KAISER_BLADES_NORMAL = (40, "Kaiser Blades Normal")
    KAISER_BLADES_TORRASQUE = (41, "Kaiser Blades Torrasque")
    TOXIC_SPORES_BROODLING = (42, "Toxic Spores Broodling")
    SPINES = (43, "Spines")
    SPINES_HARVEST = (44, "Spines Harvest")
    ACID_SPRAY_UNUSED = (45, "Acid Spray Unused")
    ACID_SPORE_NORMAL = (46, "Acid Spore Normal")
    ACID_SPORE_KUKULZAGUARDIAN = (47, "Acid Spore Kukulzaguardian")
    GLAVE_WURM_NORMAL = (48, "Glave Wurm Normal")
    GLAVE_WURM_KUKULZAMUTALISK = (49, "Glave Wurm Kukulzamutalisk")
    VENOM_UNUSEDDEFILER = (50, "Venom Unuseddefiler")
    VENOM_UNUSEDDEFILER_HERO = (51, "Venom Unuseddefiler Hero")
    SEEKER_SPORES = (52, "Seeker Spores")
    SUBTERRANEAN_TENTACLE = (53, "Subterranean Tentacle")
    SUICIDE_INFESTED_TERRAN = (54, "Suicide Infested Terran")
    SUICIDE_SCOURGE = (55, "Suicide Scourge")
    PARASITE = (56, "Parasite")
    SPAWN_BROODLINGS = (57, "Spawn Broodlings")
    ENSNARE = (58, "Ensnare")
    DARK_SWARM = (59, "Dark Swarm")
    PLAGUE = (60, "Plague")
    CONSUME = (61, "Consume")
    PARTICLE_BEAM = (62, "Particle Beam")
    PARTICLE_BEAM_HARVEST = (63, "Particle Beam Harvest")
    PSI_BLADES_NORMAL = (64, "Psi Blades Normal")
    PSI_BLADES_FENIXZEALOT = (65, "Psi Blades Fenixzealot")
    PHASE_DISRUPTOR_NORMAL = (66, "Phase Disruptor Normal")
    PHASE_DISRUPTOR_FENIXDRAGOON = (67, "Phase Disruptor Fenixdragoon")
    PSI_ASSAULT_NORMALUNUSED = (68, "Psi Assault Normalunused")
    PSI_ASSAULT_TASSADAR_ALDARIS = (69, "Psi Assault Tassadar Aldaris")
    PSIONIC_SHOCKWAVE_NORMAL = (70, "Psionic Shockwave Normal")
    PSIONIC_SHOCKWAVE_TASSADAR_ZERATUL_ARCHON = (
        71,
        "Psionic Shockwave Tassadar Zeratul Archon",
    )
    UNKNOWN72 = (72, "Unknown72")
    DUAL_PHOTON_BLASTERS_NORMAL = (73, "Dual Photon Blasters Normal")
    ANTIMATTER_MISSILES_NORMAL = (74, "Antimatter Missiles Normal")
    DUAL_PHOTON_BLASTERS_MOJO = (75, "Dual Photon Blasters Mojo")
    ANTIMATTER_MISSILES_MOJO = (76, "Antimatter Missiles Mojo")
    PHASE_DISRUPTOR_CANNON_NORMAL = (77, "Phase Disruptor Cannon Normal")
    PHASE_DISRUPTOR_CANNON_DANIMOTH = (78, "Phase Disruptor Cannon Danimoth")
    PULSE_CANNON = (79, "Pulse Cannon")
    STS_PHOTON_CANNON = (80, "Sts Photon Cannon")
    STA_PHOTON_CANNON = (81, "Sta Photon Cannon")
    SCARAB = (82, "Scarab")
    STASIS_FIELD = (83, "Stasis Field")
    PSI_STORM = (84, "Psi Storm")
    WARP_BLADES_ZERATUL = (85, "Warp Blades Zeratul")
    WARP_BLADES_DARK_TEMPLAR_HERO = (86, "Warp Blades Dark Templar Hero")
    MISSILES_UNUSED = (87, "Missiles Unused")
    LASER_BATTERY1_UNUSED = (88, "Laser Battery1 Unused")
    TORMENTOR_MISSILES_UNUSED = (89, "Tormentor Missiles Unused")
    BOMBS_UNUSED = (90, "Bombs Unused")
    RAIDER_GUN_UNUSED = (91, "Raider Gun Unused")
    LASER_BATTERY2_UNUSED = (92, "Laser Battery2 Unused")
    LASER_BATTERY3_UNUSED = (93, "Laser Battery3 Unused")
    DUAL_PHOTON_BLASTERS_UNUSED = (94, "Dual Photon Blasters Unused")
    FLECHETTE_GRENADE_UNUSED = (95, "Flechette Grenade Unused")
    TWIN_AUTOCANNONS_FLOOR_TRAP = (96, "Twin Autocannons Floor Trap")
    HELLFIRE_MISSILE_PACK_WALL_TRAP = (97, "Hellfire Missile Pack Wall Trap")
    FLAME_THROWER_WALL_TRAP = (98, "Flame Thrower Wall Trap")
    HELLFIRE_MISSILE_PACK_FLOOR_TRAP = (99, "Hellfire Missile Pack Floor Trap")
    NEUTRON_FLARE = (100, "Neutron Flare")
    DISRUPTION_WEB = (101, "Disruption Web")
    RESTORATION = (102, "Restoration")
    HALO_ROCKETS = (103, "Halo Rockets")
    CORROSIVE_ACID = (104, "Corrosive Acid")
    MIND_CONTROL = (105, "Mind Control")
    FEEDBACK = (106, "Feedback")
    OPTICAL_FLARE = (107, "Optical Flare")
    MAELSTROM = (108, "Maelstrom")
    SUBTERRANEAN_SPINES = (109, "Subterranean Spines")
    GAUSS_RIFLE0_UNUSED = (110, "Gauss Rifle0 Unused")
    WARP_BLADES_NORMAL = (111, "Warp Blades Normal")
    C10_CONCUSSION_RIFLE_SAMIR_DURAN = (112, "C10 Concussion Rifle Samir Duran")
    C10_CONCUSSION_RIFLE_INFESTED_DURAN = (113, "C10 Concussion Rifle Infested Duran")
    DUAL_PHOTON_BLASTERS_ARTANIS = (114, "Dual Photon Blasters Artanis")
    ANTIMATTER_MISSILES_ARTANIS = (115, "Antimatter Missiles Artanis")
    C10_CONCUSSION_RIFLE_ALEXEI_STUKOV = (116, "C10 Concussion Rifle Alexei Stukov")
    GAUSS_RIFLE1_UNUSED = (117, "Gauss Rifle1 Unused")
    GAUSS_RIFLE2_UNUSED = (118, "Gauss Rifle2 Unused")
    GAUSS_RIFLE3_UNUSED = (119, "Gauss Rifle3 Unused")
    GAUSS_RIFLE4_UNUSED = (120, "Gauss Rifle4 Unused")
    GAUSS_RIFLE5_UNUSED = (121, "Gauss Rifle5 Unused")
    GAUSS_RIFLE6_UNUSED = (122, "Gauss Rifle6 Unused")
    GAUSS_RIFLE7_UNUSED = (123, "Gauss Rifle7 Unused")
    GAUSS_RIFLE8_UNUSED = (124, "Gauss Rifle8 Unused")
    GAUSS_RIFLE9_UNUSED = (125, "Gauss Rifle9 Unused")
    GAUSS_RIFLE10_UNUSED = (126, "Gauss Rifle10 Unused")
    GAUSS_RIFLE11_UNUSED = (127, "Gauss Rifle11 Unused")
    GAUSS_RIFLE12_UNUSED = (128, "Gauss Rifle12 Unused")
    GAUSS_RIFLE13_UNUSED = (129, "Gauss Rifle13 Unused")
    NONE = (130, "None")
