"""Represents each StarCraft upgrade's unique upgrade ID.

These are referenced throughout various CHK sections such as UPGR, UPGS, and PUPx.
Covers all 61 upgrades (IDs 0-60).
"""

from ..richchk_enum import RichChkEnum


class UpgradeId(RichChkEnum):
    TERRAN_INFANTRY_ARMOR = (0, "Terran Infantry Armor")
    TERRAN_VEHICLE_PLATING = (1, "Terran Vehicle Plating")
    TERRAN_SHIP_PLATING = (2, "Terran Ship Plating")
    ZERG_CARAPACE = (3, "Zerg Carapace")
    ZERG_FLYER_CARAPACE = (4, "Zerg Flyer Carapace")
    PROTOSS_ARMOR = (5, "Protoss Armor")
    PROTOSS_PLATING = (6, "Protoss Plating")
    TERRAN_INFANTRY_WEAPONS = (7, "Terran Infantry Weapons")
    TERRAN_VEHICLE_WEAPONS = (8, "Terran Vehicle Weapons")
    TERRAN_SHIP_WEAPONS = (9, "Terran Ship Weapons")
    ZERG_MELEE_ATTACKS = (10, "Zerg Melee Attacks")
    ZERG_MISSILE_ATTACKS = (11, "Zerg Missile Attacks")
    ZERG_FLYER_ATTACKS = (12, "Zerg Flyer Attacks")
    PROTOSS_GROUND_WEAPONS = (13, "Protoss Ground Weapons")
    PROTOSS_AIR_WEAPONS = (14, "Protoss Air Weapons")
    PROTOSS_PLASMA_SHIELDS = (15, "Protoss Plasma Shields")
    U_238_SHELLS = (16, "U-238 Shells")
    ION_THRUSTERS = (17, "Ion Thrusters")
    BURST_LASERS = (18, "Burst Lasers (Unused)")
    TITAN_REACTOR = (19, "Titan Reactor (SV +50)")
    OCULAR_IMPLANTS = (20, "Ocular Implants")
    MOEBIUS_REACTOR = (21, "Moebius Reactor (Ghost +50)")
    APOLLO_REACTOR = (22, "Apollo Reactor (Wraith +50)")
    COLOSSUS_REACTOR = (23, "Colossus Reactor (BC +50)")
    VENTRAL_SACS = (24, "Ventral Sacs")
    ANTENNAE = (25, "Antennae")
    PNEUMATIZED_CARAPACE = (26, "Pneumatized Carapace")
    METABOLIC_BOOST = (27, "Metabolic Boost")
    ADRENAL_GLANDS = (28, "Adrenal Glands")
    MUSCULAR_AUGMENTS = (29, "Muscular Augments")
    GROOVED_SPINES = (30, "Grooved Spines")
    GAMETE_MEIOSIS = (31, "Gamete Meiosis (Queen +50)")
    METASYNAPTIC_NODE = (32, "Metasynaptic Node (Defiler +50)")
    SINGULARITY_CHARGE = (33, "Singularity Charge")
    LEG_ENHANCEMENTS = (34, "Leg Enhancements")
    SCARAB_DAMAGE = (35, "Scarab Damage")
    REAVER_CAPACITY = (36, "Reaver Capacity")
    GRAVITIC_DRIVE = (37, "Gravitic Drive")
    SENSOR_ARRAY = (38, "Sensor Array")
    GRAVITIC_BOOSTERS = (39, "Gravitic Boosters")
    KHAYDARIN_AMULET = (40, "Khaydarin Amulet (HT +50)")
    APIAL_SENSORS = (41, "Apial Sensors")
    GRAVITIC_THRUSTERS = (42, "Gravitic Thrusters")
    CARRIER_CAPACITY = (43, "Carrier Capacity")
    KHAYDARIN_CORE = (44, "Khaydarin Core (Arbiter +50)")
    UNKNOWN_UPGRADE_45 = (45, "Unknown Upgrade 45")
    UNKNOWN_UPGRADE_46 = (46, "Unknown Upgrade 46")
    ARGUS_JEWEL = (47, "Argus Jewel (Corsair +50)")
    UNKNOWN_UPGRADE_48 = (48, "Unknown Upgrade 48")
    ARGUS_TALISMAN = (49, "Argus Talisman (DA +50)")
    UNKNOWN_UPGRADE_50 = (50, "Unknown Upgrade 50")
    CADUCEUS_REACTOR = (51, "Caduceus Reactor (Medic +50)")
    CHITINOUS_PLATING = (52, "Chitinous Plating")
    ANABOLIC_SYNTHESIS = (53, "Anabolic Synthesis")
    CHARON_BOOSTER = (54, "Charon Booster")
    UNKNOWN_UPGRADE_55 = (55, "Unknown Upgrade 55")
    UNKNOWN_UPGRADE_56 = (56, "Unknown Upgrade 56")
    UNKNOWN_UPGRADE_57 = (57, "Unknown Upgrade 57")
    UNKNOWN_UPGRADE_58 = (58, "Unknown Upgrade 58")
    UNKNOWN_UPGRADE_59 = (59, "Unknown Upgrade 59")
    UNKNOWN_UPGRADE_60 = (60, "Unknown Upgrade 60")
